openapi: 3.1.0
info:
  title: Joseph - API Pericial
  description: API para realizar consultas vectoriales periciales a Joseph.
  version: "1.0.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://joseph-pasarela.onrender.com
paths:
  /consulta:
    post:
      summary: Realiza una consulta vectorial entre los informes periciales.
      operationId: consultaInformes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConsultaRequest"
      responses:
        '200':
          description: Resultados similares encontrados
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsultaResponse"
components:
  schemas:
    ConsultaRequest:
      type: object
      properties:
        query:
          type: string
          description: Texto de la consulta
          example: daños por cortocircuito en cuadro eléctrico
        n_resultados:
          type: integer
          description: Número de resultados a devolver
          default: 5
    ConsultaResponse:
      type: object
      properties:
        resultados:
          type: array
          items:
            $ref: "#/components/schemas/FragmentoInforme"
    FragmentoInforme:
      type: object
      properties:
        id:
          type: string
          description: ID del documento
          example: 1234
        texto:
          type: string
          description: Fragmento del informe pericial relacionado
          example: Se observa afectación en el cuadro eléctrico general...